export const themes = {
    light: {
        name: 'light',
        primary: '#1976d2',
        border: '#e0e0e0',
        headerBg: '#f5f5f5',
        sortedHeaderBg: '#eaf3ff',
        sortedHeaderBorder: '#1976d2',
        sortedHeaderText: '#0d47a1',
        text: '#212121',
        textSec: '#757575',
        hover: '#eeeeee',
        select: '#e3f2fd',
        background: '#fff',
        sidebarBg: '#fafafa',
        pinnedBoundaryShadow: 'rgba(15,23,42,0.22)'
    },
    dark: {
        name: 'dark',
        isDark: true,
        primary: '#818CF8',
        border: 'rgba(255,255,255,0.10)',
        borderStrong: 'rgba(255,255,255,0.16)',
        headerBg: '#111318',
        headerSubtleBg: '#171A21',
        pageBg: '#0A0C10',
        surfaceBg: '#090C11',
        surfaceMuted: '#0D1117',
        surfaceInset: '#11161E',
        hierarchyBg: '#0F141C',
        sortedHeaderBg: 'rgba(129,140,248,0.12)',
        sortedHeaderBorder: '#818CF8',
        sortedHeaderText: '#C7D2FE',
        text: '#F8FAFC',
        textSec: '#CBD5E1',
        textSoft: '#94A3B8',
        hover: '#171B22',
        hoverStrong: '#1C212B',
        select: 'rgba(129,140,248,0.16)',
        background: '#0F1218',
        sidebarBg: '#10141B',
        totalBg: 'rgba(129,140,248,0.18)',
        totalBgStrong: '#818CF8',
        totalText: '#EEF2FF',
        totalTextStrong: '#0A0C10',
        shadowSm: '0 1px 2px rgba(0,0,0,0.35)',
        shadowMd: '0 18px 40px rgba(0,0,0,0.42), 0 2px 10px rgba(0,0,0,0.28)',
        shadowInset: 'inset 0 1px 0 rgba(255,255,255,0.03)',
        pinnedBoundaryShadow: 'rgba(0,0,0,0.65)',
        radius: '16px',
        radiusSm: '10px',
    },
    material: {
        name: 'material',
        primary: '#6200ee',
        border: '#e0e0e0',
        headerBg: '#fff',
        sortedHeaderBg: '#f3edff',
        sortedHeaderBorder: '#6200ee',
        sortedHeaderText: '#3b1f80',
        text: '#000',
        textSec: '#666',
        hover: '#f5f5f5',
        select: '#e8eaf6',
        background: '#fff',
        sidebarBg: '#fafafa',
        pinnedBoundaryShadow: 'rgba(17,24,39,0.22)'
    },
    balham: {
        name: 'balham',
        primary: '#0091ea',
        border: '#BDC3C7',
        headerBg: '#F5F7F7',
        sortedHeaderBg: '#e8f4fd',
        sortedHeaderBorder: '#0091ea',
        sortedHeaderText: '#0b4f75',
        text: '#2c3e50',
        textSec: '#7f8c8d',
        hover: '#ecf0f1',
        select: '#d6eaf8',
        background: '#fff',
        sidebarBg: '#fafafa',
        pinnedBoundaryShadow: 'rgba(15,23,42,0.22)'
    },
    flash: {
        name: 'flash',
        primary: '#4F46E5',
        border: '#E5E7EB',
        borderStrong: '#D7DDEA',
        headerBg: '#FFFFFF',
        headerSubtleBg: '#F9FAFB',
        pageBg: '#FFFFFF',
        surfaceBg: '#FFFFFF',
        surfaceMuted: '#F8FAFC',
        surfaceInset: '#F5F7FB',
        hierarchyBg: '#F7F9FC',
        sortedHeaderBg: 'rgba(79,70,229,0.06)',
        sortedHeaderBorder: '#4F46E5',
        sortedHeaderText: '#3730A3',
        text: '#111827',
        textSec: '#475569',
        textSoft: '#64748B',
        hover: '#F8FAFC',
        hoverStrong: '#F3F4F6',
        select: 'rgba(79,70,229,0.08)',
        background: '#FFFFFF',
        sidebarBg: '#FFFFFF',
        totalBg: 'rgba(238,242,255,0.82)',
        totalBgStrong: 'rgba(224,231,255,0.95)',
        totalText: '#3730A3',
        totalTextStrong: '#312E81',
        shadowSm: '0 1px 2px rgba(15,23,42,0.05)',
        shadowMd: '0 10px 24px rgba(15,23,42,0.06), 0 2px 8px rgba(15,23,42,0.04)',
        shadowInset: 'inset 0 1px 0 rgba(255,255,255,0.8)',
        pinnedBoundaryShadow: 'rgba(79,70,229,0.12)',
        radius: '16px',
        radiusSm: '10px',
    },
    blooomberg: {
        name: 'blooomberg',
        isDark: true,
        primary: '#F59E0B',
        border: 'rgba(255,255,255,0.10)',
        borderStrong: 'rgba(255,255,255,0.16)',
        headerBg: '#14181E',
        headerSubtleBg: '#1A2028',
        pageBg: '#0A0D12',
        surfaceBg: '#080B10',
        surfaceMuted: '#0D1219',
        surfaceInset: '#111822',
        hierarchyBg: '#0F151E',
        sortedHeaderBg: 'rgba(245,158,11,0.16)',
        sortedHeaderBorder: '#F59E0B',
        sortedHeaderText: '#FCD34D',
        text: '#F3F4F6',
        textSec: '#D1D5DB',
        textSoft: '#9CA3AF',
        hover: '#1A212B',
        hoverStrong: '#202833',
        select: 'rgba(245,158,11,0.18)',
        background: '#0F1319',
        sidebarBg: '#10151D',
        totalBg: 'rgba(245,158,11,0.16)',
        totalBgStrong: '#F59E0B',
        totalText: '#111111',
        totalTextStrong: '#000000',
        shadowSm: '0 1px 2px rgba(0,0,0,0.35)',
        shadowMd: '0 18px 40px rgba(0,0,0,0.45), 0 2px 10px rgba(0,0,0,0.30)',
        shadowInset: 'inset 0 1px 0 rgba(255,255,255,0.03)',
        pinnedBoundaryShadow: 'rgba(0,0,0,0.72)',
        radius: '12px',
        radiusSm: '8px',
    },
    bloomblerg_black: {
        name: 'bloomblerg_black',
        isDark: true,
        primary: '#F59E0B',
        border: 'rgba(255,255,255,0.18)',
        borderStrong: 'rgba(255,255,255,0.28)',
        headerBg: '#000000',
        headerSubtleBg: '#0A0A0A',
        pageBg: '#000000',
        surfaceBg: '#000000',
        surfaceMuted: '#050505',
        surfaceInset: '#0B0B0B',
        hierarchyBg: '#080808',
        sortedHeaderBg: 'rgba(245,158,11,0.22)',
        sortedHeaderBorder: '#F59E0B',
        sortedHeaderText: '#FFFFFF',
        text: '#FFFFFF',
        textSec: 'rgba(255,255,255,0.88)',
        textSoft: 'rgba(255,255,255,0.68)',
        hover: '#101010',
        hoverStrong: '#171717',
        select: 'rgba(245,158,11,0.20)',
        background: '#000000',
        sidebarBg: '#020202',
        totalBg: 'rgba(245,158,11,0.20)',
        totalBgStrong: '#F59E0B',
        totalText: '#FFFFFF',
        totalTextStrong: '#000000',
        shadowSm: '0 1px 2px rgba(0,0,0,0.35)',
        shadowMd: '0 18px 40px rgba(0,0,0,0.45), 0 2px 10px rgba(0,0,0,0.30)',
        shadowInset: 'inset 0 1px 0 rgba(255,255,255,0.06)',
        pinnedBoundaryShadow: 'rgba(0,0,0,0.72)',
        radius: '12px',
        radiusSm: '8px',
    },
    strata: {
        name: 'strata',
        isDark: true,
        primary: '#00f2ff',
        border: 'rgba(255,255,255,0.08)',
        headerBg: 'rgba(12,12,18,0.98)',
        sortedHeaderBg: 'rgba(0,242,255,0.08)',
        sortedHeaderBorder: '#00f2ff',
        sortedHeaderText: '#00f2ff',
        text: '#e0e0e6',
        textSec: '#8a8a98',
        hover: 'rgba(255,255,255,0.04)',
        select: 'rgba(0,242,255,0.12)',
        background: '#0d0d12',
        sidebarBg: '#0a0a10',
        pinnedBoundaryShadow: 'rgba(0,0,0,0.7)',
        radius: '8px',
    },
    crystal: {
        name: 'crystal',
        isDark: true,
        primary: '#00f2ff',
        border: 'rgba(255,255,255,0.08)',
        headerBg: 'rgba(3,7,18,0.92)',
        sortedHeaderBg: 'rgba(0,242,255,0.08)',
        sortedHeaderBorder: '#00f2ff',
        sortedHeaderText: '#00f2ff',
        text: '#f9fafb',
        textSec: '#9ca3af',
        hover: 'rgba(255,255,255,0.03)',
        select: 'rgba(0,242,255,0.1)',
        background: '#030712',
        sidebarBg: '#050b1a',
        pinnedBoundaryShadow: 'rgba(0,0,0,0.8)',
        radius: '8px',
    },
    alabaster: {
        name: 'alabaster',
        primary: '#2563eb',
        border: 'rgba(0,0,0,0.06)',
        headerBg: '#fcfcfc',
        sortedHeaderBg: 'rgba(37,99,235,0.05)',
        sortedHeaderBorder: '#2563eb',
        sortedHeaderText: '#1e40af',
        text: '#0a0a0a',
        textSec: '#666666',
        hover: 'rgba(37,99,235,0.04)',
        select: 'rgba(37,99,235,0.08)',
        background: '#ffffff',
        sidebarBg: '#fcfcfc',
        pinnedBoundaryShadow: 'rgba(0,0,0,0.06)',
        radius: '8px',
    },
    satin: {
        name: 'satin',
        primary: '#0f172a',
        border: 'rgba(0,0,0,0.04)',
        headerBg: 'rgba(255,255,255,0.8)',
        sortedHeaderBg: '#f1f5f9',
        sortedHeaderBorder: '#0f172a',
        sortedHeaderText: '#0f172a',
        text: '#0f172a',
        textSec: '#64748b',
        hover: 'rgba(248,250,252,0.8)',
        select: '#f1f5f9',
        background: '#ffffff',
        sidebarBg: '#fdfdfd',
        pinnedBoundaryShadow: 'rgba(0,0,0,0.04)',
        radius: '12px',
    }
};

export const gridDimensionTokens = Object.freeze({
    density: Object.freeze({
        spacingLabels: Object.freeze(['Compact', 'Normal', 'Loose']),
        rowHeights: Object.freeze([36, 44, 56])
    }),
    columnWidths: Object.freeze({
        schemaFallback: 180,
        rowNumber: 56,
        hierarchy: 320,
        dimension: 190,
        measure: 170,
        subtotal: 170,
        collapsedPlaceholder: 60
    }),
    autoSize: Object.freeze({
        headerPadding: 40,
        headerOverscan: 12,
        cellPadding: 24,
        cellOverscan: 6,
        minWidth: 60,
        maxWidth: 600
    })
});

export const mergeStateStyles = (...layers) =>
    layers.reduce((merged, layer) => {
        if (!layer || typeof layer !== 'object') return merged;
        Object.entries(layer).forEach(([key, value]) => {
            if (value === undefined || value === null) return;
            if (key === 'boxShadow' && merged.boxShadow) {
                merged.boxShadow = `${merged.boxShadow}, ${value}`;
                return;
            }
            merged[key] = value;
        });
        return merged;
    }, {});

export const isDarkTheme = (theme) => theme && (theme.name === 'dark' || theme.isDark === true);

export const getStyles = (theme) => {
    const r = theme.radius || '4px';
    const rs = theme.radiusSm || '8px';
    return ({
    root: {
        display: 'flex',
        flexDirection: 'column',
        fontFamily: "'Inter', ui-sans-serif, system-ui, sans-serif",
        height: '100%',
        background: theme.pageBg || theme.background,
        border: `1px solid ${theme.border}`,
        borderRadius: r,
        overflow: 'hidden',
        fontSize: '13px',
        color: theme.text,
        boxShadow: theme.shadowMd || 'none'
    },
    appBar: {
        minHeight: '60px',
        borderBottom: `1px solid ${theme.border}`,
        display: 'flex',
        alignItems: 'center',
        padding: '0 18px',
        justifyContent: 'space-between',
        background: theme.headerBg,
        color: theme.text,
        boxShadow: theme.shadowInset || 'none'
    },
    searchBox: {
        display: 'flex',
        alignItems: 'center',
        background: theme.isDark ? 'rgba(255,255,255,0.08)' : (theme.headerSubtleBg || '#F3F4F6'),
        borderRadius: rs,
        padding: '4px 8px',
        width: '200px',
        boxShadow: theme.isDark ? 'none' : (theme.shadowInset || 'none')
    },
    sidebar: {
        width: '288px',
        minWidth: '288px',
        borderRight: `1px solid ${theme.border}`,
        background: theme.sidebarBg,
        display: 'flex',
        flexDirection: 'column',
        padding: '18px 14px',
        gap: '18px',
        overflowY: 'auto'
    },
    sectionTitle: {
        fontSize: '13px',
        fontWeight: 500,
        color: theme.text,
        marginBottom: '12px',
        display: 'flex',
        alignItems: 'center',
        gap: '8px'
    },
    sectionTitleSm: {
        fontSize: '11px',
        fontWeight: 700,
        letterSpacing: '0.06em',
        textTransform: 'uppercase',
        color: theme.textSec,
        marginBottom: '8px',
        display: 'flex',
        alignItems: 'center',
        gap: '6px'
    },
    chip: {
        background: theme.isDark ? 'rgba(255,255,255,0.07)' : '#ffffff',
        border: `1px solid ${theme.border}`,
        borderRadius: rs,
        padding: '6px 10px',
        marginBottom: '6px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        cursor: 'grab',
        boxShadow: theme.shadowSm || '0 1px 2px rgba(0,0,0,0.05)',
        position: 'relative',
        color: theme.text,
        transition: 'border-color 120ms ease, background 120ms ease, box-shadow 120ms ease'
    },
    dropZone: {
        minHeight: '52px',
        maxHeight: '140px',
        overflowY: 'auto',
        border: theme.isDark ? `1px solid ${theme.border}` : '1px solid #F3F4F6',
        borderRadius: rs,
        padding: '8px',
        background: theme.isDark ? 'rgba(255,255,255,0.02)' : (theme.surfaceInset || 'rgba(249,250,251,0.5)'),
        boxShadow: theme.isDark ? 'none' : (theme.shadowInset || 'none')
    },
    main: {
        flex: 1,
        overflow: 'hidden',
        position: 'relative',
        display: 'flex',
        flexDirection: 'column',
        background: theme.pageBg || theme.background,
        borderRadius: `0 0 ${r} ${r}`
    },
    scrollContainer: {
        flex: 1,
        overflow: 'auto',
        position: 'relative',
        background: theme.pageBg || theme.background,
        borderRadius: `0 0 ${r} ${r}`
    },
    headerSticky: {
        position: 'sticky',
        top: 0,
        zIndex: 100,
        background: theme.headerBg,
        width: 'fit-content',
        minWidth: '100%',
        boxShadow: theme.shadowInset || 'none',
        borderTopLeftRadius: r,
        borderTopRightRadius: r,
        overflow: 'visible'
    },
    headerRow: {
        display: 'flex',
        width: '100%'
    },
    headerCell: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '0 12px',
        borderRight: `1px solid ${theme.border}`,
        borderBottom: `1px solid ${theme.border}`,
        fontWeight: 600,
        color: theme.text,
        position: 'relative',
        boxSizing: 'border-box',
        flexShrink: 0,
        minWidth: 0,
        overflow: 'hidden',
        whiteSpace: 'nowrap',
        textOverflow: 'ellipsis',
        background: theme.headerBg,
        boxShadow: theme.shadowInset || 'none'
    },
    pinned: {
        position: 'sticky',
        zIndex: 3,
        background: theme.surfaceBg || theme.background
    },
    pinnedLeft: {
        left: 0,
        borderRight: `1px solid ${theme.border}`
    },
    pinnedRight: {
        right: 0,
        borderLeft: `1px solid ${theme.border}`
    },
    row: {
        display: 'flex',
        position: 'absolute',
        left: 0,
        width: '100%',
        boxSizing: 'border-box'
    },
    cell: {
        display: 'flex',
        alignItems: 'center',
        padding: '0 12px',
        borderRight: `1px solid ${theme.border}`,
        borderBottom: `1px solid ${theme.border}`,
        background: theme.surfaceBg || theme.background,
        color: theme.text,
        overflow: 'hidden',
        whiteSpace: 'nowrap',
        boxSizing: 'border-box',
        flexShrink: 0,
        lineHeight: 1.45
    },
    cellSelected: {
        background: `${theme.select} !important`,
        boxShadow: `inset 0 0 0 2px ${theme.primary}`,
        zIndex: 2,
        position: 'relative'
    },
    btn: {
        padding: '4px 10px',
        borderRadius: rs,
        border: `1px solid transparent`,
        background: 'transparent',
        cursor: 'pointer',
        fontSize: '12px',
        display: 'inline-flex',
        alignItems: 'center',
        gap: '5px',
        fontWeight: 500,
        color: theme.text,
        whiteSpace: 'nowrap',
        lineHeight: 1.5,
        transition: 'background 120ms ease, border-color 120ms ease, box-shadow 120ms ease',
        userSelect: 'none',
    },
    dropLine: {
        position: 'absolute',
        height: '2px',
        background: theme.primary,
        left: 0, right: 0, zIndex: 10, pointerEvents: 'none'
    },
    expandedSeparator: {
        borderBottom: `2px solid ${theme.primary}`
    },
    toolPanelSection: {
        display: 'flex',
        flexDirection: 'column',
        borderBottom: `1px solid ${theme.border}44`,
        marginBottom: '4px',
        transition: 'all 0.3s ease-in-out'
    },
    toolPanelSectionHeader: {
        display: 'flex',
        alignItems: 'center',
        padding: '8px 12px',
        background: theme.headerSubtleBg || theme.headerBg,
        cursor: 'pointer',
        fontSize: '11px',
        fontWeight: 600,
        textTransform: 'uppercase',
        color: theme.textSec,
        userSelect: 'none',
        transition: 'background 0.2s'
    },
    toolPanelList: {
        display: 'flex',
        flexDirection: 'column',
        padding: '4px 0',
        transition: 'height 0.3s ease'
    },
    columnItem: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        padding: '6px 12px',
        fontSize: '12px',
        cursor: 'default',
        transition: 'background 0.2s, transform 0.2s',
        position: 'relative',
        userSelect: 'none'
    }
}); };
